outlining_task:
  description: >
    Create a comprehensive outline for a blog post written in UK English.
    The blog post description is as follows:
    {description}
  expected_output: >
    The post should use UK English spelling and grammar.
    The outline should include a catchy title at the start to appeal to someone browsing the posts of the blog.
    After the title, indicate that there should be a few sentences of friendly introduction to the post material.
    Then outline the headers and subheaders for the rest of the post with a very brief note of the content that goes in each section.
    Only use level 2 and level 3 headers for the outline.
    The headers should use title case.
    The final header must be a level 2 header called "Wrapping Up" and needs to include a summary of the post and a call to action.
  agent: outliner

drafting_task:
  description: >
    Flesh out the contents of a blog post based on the outline provided.
    The description of the blog post is as follows:
    {description}
  expected_output: >
    The post should use UK English spelling and grammar.
    The post should be written in a friendly and engaging style, suitable for publication on a blog about software development, software tools and software architecture.
    Remember that the audience is made up of amateur and professional software engineers trying to develop their knowledge and competence.
    There is no need to focus on the concerns that businesses or managers might have surrounding the topic.
    The post must adhere to the outline provided, but you can add additional detail and examples as needed.
    The post should not exceed a read time of 10 minutes, but this is not a target to aim for.
  agent: writer

refinement_task:
  description: >
    Review the blog post given and produce a refined version, ensuring the post is easy to follow and covers the topic thoroughly.
    For reference, the description of the blog post is as follows:
    {description}
  expected_output: >
    A refined version of the blog post, using UK English spelling and grammar.
    The post should be written in a friendly and engaging style, suitable for publication on a blog about software development, software tools and software architecture.
    Remember that the audience is made up of amateur and professional software engineers trying to develop their knowledge and competence.
    There is no need to focus on the concerns that businesses or managers might have surrounding the topic.
  agent: writer

convert_to_markdown_task:
  description: >
    Format the given blog post into markdown, ensuring it follows the style guide.
    The blog post description is as follows:
    {description}
  expected_output: >
    A markdown version of the document from the editor.
    None of the original material should be changed, but it can be reformatted to fit the requirements of the markdown format.

    Your output must strictly be just the markdown content, with no other explanations or comments.
    The post should be output without '```' fences surrounding it, as if it is being written directly into a markdown file.

    The document must adhere to the following style guide:

    - All titles and headers must use title case.
    - Put each sentence on a new line.
    - A level 1 header containing the blog title must be used in the first line of the post.
    - The title will be followed by the friendly introduction text for the post, before any other headings.
    - Headings and sub-headings will use level 2 and level 3 headers.
    - Code must be formatted as code blocks with the correct language highlighting.
    - The final header of the post will be a level 2 heading titled "Wrapping Up".
    - Unordered lists must use hyphens as bullet points.
    - Ordered lists must use 1. for every item.
  agent: markdown_expert
